version: '3.8'

services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: historia
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/historia
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db

  weaviate:
    image: semitechnologies/weaviate:1.21.1
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'

volumes:
  db_data:
